#define COMMA                           1
#define ASSIGN                          2
#define LOR                             3
#define LAND                            4
#define LNOT                            5
#define DOUBLE_LNOT                     6
#define EQ                              7
#define LE                              8
#define LT                              9
#define GE                             10
#define GT                             11
#define NE                             12
#define BITOR                          13
#define BITXOR                         14
#define BITAND                         15
#define LSHIFT                         16
#define RSHIFT                         17
#define PLUS                           18
#define MINUS                          19
#define DIVIDE                         20
#define MULTIPLY                       21
#define MOD                            22
#define UNARY                          23
#define IFX                            24
#define IFNOT                          25
#define ELSE                           26
#define NAME                           27
#define NUMBER                         28
#define BITNOT                         29
#define SEMICOLON                      30
#define LBRACKET                       31
#define RBRACKET                       32
#define IF                             33
#define LPAREN                         34
#define RPAREN                         35
#define WHILE                          36
