#define COMMA                           1
#define ASSIGN                          2
#define LOR                             3
#define LAND                            4
#define LNOT                            5
#define DOUBLE_LNOT                     6
#define EQ                              7
#define LE                              8
#define LT                              9
#define GE                             10
#define GT                             11
#define NE                             12
#define BITOR                          13
#define BITXOR                         14
#define BITAND                         15
#define LSHIFT                         16
#define RSHIFT                         17
#define PLUS                           18
#define MINUS                          19
#define DIVIDE                         20
#define MULTIPLY                       21
#define MOD                            22
#define UNARY                          23
#define BITNOT                         24
#define NUMBER                         25
#define NAME                           26
#define IFX                            27
#define IFNOT                          28
#define ELSE                           29
#define ACTIONNAME                     30
#define LSQBRACKET                     31
#define RSQBRACKET                     32
#define LPAREN                         33
#define RPAREN                         34
#define FUNCCALL                       35
#define VAR                            36
#define SEMICOLON                      37
#define LBRACKET                       38
#define RBRACKET                       39
#define IF                             40
#define WHILE                          41
#define FOR                            42
#define COLON                          43
#define CONTINUE                       44
#define BREAK                          45
#define FUNCTION                       46
#define RETURN                         47
